language: ruby
cache:
- bundler
before_install: gem install bundler -v 1.15
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- gem build sensu-plugins-systemd.gemspec
- gem install sensu-plugins-systemd-*.gem
- bundle exec rake default
deploy:
  provider: rubygems
  api_key:
    secure: Hf1ZRHiWtWvOlcoLmcFJSql688r7s8CkTRUO5FYvUBjJE/x/P2+UDFONcYzycEAkLXzv9MIMXHO8vZ2m5rVSqbiP055+MtzRnukO2OaF2Ke0vYCuArOxj/LvhKAuLJRVNYbD138MltCnqUMjU2Ks4b4Z/wtHqSkbOoBsyTwwpYq0HiCbQyGNkacGzMZ44vnPR3cS0TrljjwYhnn1gDKkEkQf1p3iNrmIIapspU64U36KsxaGccFiXo2YSI9vBY+kssfGIOB5YAXoFHQ3YqdTpGMy7Q587IttlIlPQwhvYvK9lCZMZSCxmaZMGq2zy+3ttKe9CEejPGAtaPkiYrmmuM1hZUgQDk94znsTitpZxX5vlFMv5BUnxiOHcL+aQKFG4DlTj7KD+7a0BPb3AbUeD2njql6elCXiGeqzKgjS5x9W7WDZdoMj8VdQWzs+hh98C9yY5DDipp13yGJ3gqzKmKRbaHXUA9wLY4ic0022+ZwxCKX5TKqjOAi8WmQSCG19r+/uIaFY5MeTE7wrsuA0oSWM5YA9UaJNf5WbpUpC9tLG2owvAOjtEwhBBS9EijhiME8ABKBqp/RWJYqrj8PDrucDYLm2pB2PzlLKqs/+UQ//Rh4U/TKRLdWBrCevVr5hw6TLRl5ThoEjL1heqHsoH3X51rhtt3MBleYkawn37jg=
  gem: sensu-plugins-systemd
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-systemd
